name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './'  # Path to your build/artifact directory

      - name: Deploy to GitHub Pages (pages branch)
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          branch: pages  # Deploying to the 'pages' branch

      - name: Update -pages branch with Deployment Link
        run: |
          # Create a temp directory
          mkdir temp-pages
          cd temp-pages
          git init
          git remote add origin https://github.com/${{ github.repository }}.git
          
          # Check out the '-pages' branch
          git fetch origin
          git checkout pages

          # Create a file to store the deployment link
          echo "Deployment URL: ${{ steps.deployment.outputs.page_url }}" > deployment_link.txt
          git add deployment_link.txt
          git commit -m "Add deployment link"
          git push origin pages
